Linear Algebra

Inverse of a matrix

In [2]:
import numpy as np
from scipy import linalg
matrix = np.array([[10,2],[3,5]])
matrix

array([[10,  2],
       [ 3,  5]])

In [3]:
type(matrix)

numpy.ndarray

In [4]:
linalg.inv(matrix)

array([[ 0.11363636, -0.04545455],
       [-0.06818182,  0.22727273]])

Finding Determinant

In [5]:
import numpy as np
from scipy import linalg
matrix = np.array([[10,2],[3,5]])
matrix

array([[10,  2],
       [ 3,  5]])

In [6]:
linalg.det(matrix)

44.0

solve linear equations

In [7]:
numArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
numArrayValue = np.array([21,9,6])


In [8]:
linalg.solve(numArray,numArrayValue)

C:\Users\YashnNaisha\anaconda3\lib\site-packages\ipykernel_launcher.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=1.54198e-18): result may not be accurate.
  """Entry point for launching an IPython kernel.


array([-4.05323966e+16,  8.10647933e+16, -4.05323966e+16])

Single value decomposition

In [9]:
linalg.svd(numArray)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [10]:
# unitary matrix , sigma or square root of eigen values , VH is values collected into unitary matrix 